-- Disable RLS for development
ALTER TABLE options DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE units DISABLE ROW LEVEL SECURITY;
ALTER TABLE problems DISABLE ROW LEVEL SECURITY;
ALTER TABLE attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE study_time_logs DISABLE ROW LEVEL SECURITY;
